### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by 3jq** [RealzPrestige/Pyro-1.4.1_deobf#2]
binscure deobfuscator?

**Comment by moaji** [comment]
binscure 0.4 funny

**Comment by fuckyouthinkimboogieman** [comment]
no its not binscure 0.4 lmfao

**Comment by fuckyouthinkimboogieman** [comment]
nuker has binscure

**Comment by Crystallinqq** [comment]
its not deobfuscated its just a decompile of a non obfuscated jar

**Comment by fuckyouthinkimboogieman** [comment]
oh lol

**Comment by fuckyouthinkimboogieman** [comment]
um @Crystallinqq well its just summit i just understood it lmfao
