### ISSUE TITLE
Post original “deobf” jar

### ISSUE THREAD

**Issue by Crystallinqq** [RealzPrestige/Pyro-1.4.1_deobf#9]
post ur non obfuscated jar cuz ur decompiler is shit and i want to decompile it myself

**Comment by HausemasterIssue** [comment]
> 
> 
> post ur non obfuscated jar cuz ur decompiler is shit and i want to decompile it myself
2 things qq.

1. most of the code has been deobfuscated which is a lot better than none, and you decompiling it wouldn't really make a difference. besides, it's basically summit anyway so who tf cares.

2. https://github.com/HausemasterIssue/Future-v2.9-Dump-Semi-Deobf <--- i am retarded so i decided to check your future crack using the horrible threadtear using cfr to deobf/decompile 🤢 could you take a look at these and explain them please
[qq.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245371/qq.txt)
[is.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245374/is.txt)
[sussy.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245377/sussy.txt)
[baka.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245378/baka.txt)
[haha.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245379/haha.txt)
[lol.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245380/lol.txt)
[what.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245382/what.txt)

**Comment by moaji** [comment]
> > post ur non obfuscated jar cuz ur decompiler is shit and i want to decompile it myself
> > 2 things qq.
> 
>     1. most of the code has been deobfuscated which is a lot better than none, and you decompiling it wouldn't really make a difference. besides, it's basically summit anyway so who tf cares.
> 
>     2. https://github.com/HausemasterIssue/Future-v2.9-Dump-Semi-Deobf <--- i am retarded so i decided to check your future crack using the horrible threadtear using cfr to deobf/decompile 🤢 could you take a look at these and explain them please
>        [qq.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245371/qq.txt)
>        [is.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245374/is.txt)
>        [sussy.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245377/sussy.txt)
>        [baka.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245378/baka.txt)
>        [haha.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245379/haha.txt)
>        [lol.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245380/lol.txt)
>        [what.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245382/what.txt)

It's not basically summit it's literally refactored summit.

**Comment by HausemasterIssue** [comment]
lol, description for strafe is exact same as summit

**Comment by Crystallinqq** [comment]
ya ok this is just summit Lol sorry i was on phone whe ni was lookin at it loel

**Comment by Crystallinqq** [comment]
> > post ur non obfuscated jar cuz ur decompiler is shit and i want to decompile it myself
> > 2 things qq.
> 
> 1. most of the code has been deobfuscated which is a lot better than none, and you decompiling it wouldn't really make a difference. besides, it's basically summit anyway so who tf cares.
> 2. https://github.com/HausemasterIssue/Future-v2.9-Dump-Semi-Deobf <--- i am retarded so i decided to check your future crack using the horrible threadtear using cfr to deobf/decompile 🤢 could you take a look at these and explain them please
>    [qq.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245371/qq.txt)
>    [is.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245374/is.txt)
>    [sussy.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245377/sussy.txt)
>    [baka.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245378/baka.txt)
>    [haha.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245379/haha.txt)
>    [lol.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245380/lol.txt)
>    [what.txt](https://github.com/RealzPrestige/Pyro-1.4.1_deobf/files/7245382/what.txt)

u must be retarded. that is all just auth shit, alt manager stuff or module related classes

**Comment by ProfKambing** [comment]
bro u know this is faked right OOLOLOLOOL XDDDDDDD

**Comment by HausemasterIssue** [comment]
we do a minisclue amount of trlling :trollface:
